---


- name: "Configure PVE migration security"
  lineinfile:
    path: /etc/pve/datacenter.cfg
    backrefs: no
    regexp: "^migration:.+$"
    line: "migration: type={{ proxmox_ve__migration_secure | ternary('secure', 'insecure') }}"
    state: "present"
    backup: yes
    create: yes
    unsafe_writes: yes
