---

- name: "Make sure PVE configuration file exists"
  file:
    path: /etc/pve/datacenter.cfg
    state: file
    mode: 0660
    owner: root
    group: root

- name: "Configure PVE migration security"
  lineinfile:
    path: /etc/pve/datacenter.cfg
    backrefs: yes
    regexp: "^#?[ \t]*migration:.+$"
    line: "migration: type={{ proxmox_ve__migration_secure | ternary('secure', 'insecure') }}"
    state: "present"
    backup: yes
