---

- name: Check if prometheus pve user exist
  ansible.builtin.command: /usr/sbin/pveum user list
  register: pve_user_list
  check_mode: no
  changed_when: pve_user_list.rc != 0


- name: Create prometheus pve user
  ansible.builtin.command: "/usr/sbin/pveum user add {{ proxmox_ve__spv_user }} -password {{ proxmox_ve__spv_password }}"
  when: proxmox_ve__spv_user not in pve_user_list.stdout
  register: pveum_output
  changed_when: pveum_output.rc != 0

- name: Create prometheus pve user
  ansible.builtin.command: "/usr/sbin/pveum aclmod / -user {{ proxmox_ve__spv_user }} -role PVEAuditor"
  when: proxmox_ve__spv_user not in pve_user_list.stdout
  register: pveum_output
  changed_when: pveum_output.rc != 0
