---

- name: "Create PVE datacenter configuration file"
  ansible.builtin.file:
    path: /etc/pve/datacenter.cfg
    state: touch
    owner: root
    group: www-data
    mode: 0640

- name: "Configure PVE migration security"
  ansible.builtin.lineinfile:
    path: /etc/pve/datacenter.cfg
    backrefs: no
    regexp: "^migration:.+$"
    line: "migration: type={{ proxmox_ve__migration_secure | ternary('secure', 'insecure') }}"
    state: "present"
    backup: yes
    create: no
    unsafe_writes: yes
