---

- name: Install APT https transport
  ansible.builtin.apt:
    package: apt-transport-https
    state: present


- name: Removing well known repo files
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/{{ item }}
    state: absent
  with_items:
    - "{{ proxmox_ve__apt_repo_todel }}"

# Needed because default installation of Proxmox VE comses with
# ceph repository file which fail the installation
- name: Checking ceph repo file
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/ceph.list
    regexp: '^deb .*enterprise.proxmox.com.*'
    state: "{{ 'present' if proxmox_ve__enterprise else 'absent' }}"

- name: Install Proxmox VE apt repository Debian before 13 Trixie
  when: ansible_distribution_version is version('13', '<')
  block:
  - name: Register repository signing key
    ansible.builtin.apt_key:
      url: "{{ proxmox_ve__apt_repo_key[ansible_distribution_release] }}"

  - name: Add no-subscription repository
    ansible.builtin.apt_repository:
      repo: "{{ proxmox_ve__apt_repo_pve_no_subscription }}"
      state: present
      update_cache: yes

  - name: Add enterprise repository
    ansible.builtin.apt_repository:
      repo: "{{ proxmox_ve__apt_repo_pve_enterprise }}"
      state: present
      update_cache: yes
    when:
      - proxmox_ve__enterprise

- name: Install Proxmox VE apt repository Debian 13 Trixie and later
  when: ansible_distribution_version is version('13', '>=')
  block:
  - name: Add no-subscription repository
    ansible.builtin.deb822_repository:
      name: proxmox
      types: deb
      uris: "http://download.proxmox.com/debian/pve"
      suites: "{{ ansible_distribution_release | lower }}"
      components: pve-no-subscription
      signed_by: "{{ proxmox_ve__apt_repo_key[ansible_distribution_release | lower] }}"
      state: present

  - name: Add enterprise repository
    ansible.builtin.deb822_repository:
      name: pve-enterprise
      types: deb
      uris: "https://enterprise.proxmox.com/debian/pve"
      suites: "{{ ansible_distribution_release | lower }}"
      components: pve-enterprise
      signed_by: "{{ proxmox_ve__apt_repo_key[ansible_distribution_release | lower] }}"
      state: present
    when:
      - proxmox_ve__enterprise

- name: Get list of installed packages
  ansible.builtin.package_facts:
    manager: apt

# Must install ifupdown2 before proxmox-ve otherwise network connection
# will be closed during upgrade
- name: Install ifupdown2
  ansible.builtin.apt:
    package: ifupdown2
    state: present
    update_cache: yes
  notify: Reboot Host
  when: 
    - "'proxmox-ve' not in ansible_facts.packages"
    - ansible_distribution_release == "bullseye"

- name: Install Proxmox VE software
  ansible.builtin.apt:
    package: proxmox-ve
    state: present
    update_cache: yes
  notify: Reboot Host
