---

- name: Install APT https transport
  ansible.builtin.apt:
    package: apt-transport-https
    state: present

- name: Register repository signing key
  ansible.builtin.apt_key:
    url: "{{ proxmox_ve__apt_repo_key[ansible_distribution_release] }}"

- name: Removing well known repo files
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/{{ item }}
    state: absent
  with_items:
    - "{{ proxmox_ve__apt_repo_todel }}"

- name: Add no-subscription repository
  ansible.builtin.apt_repository:
    repo: "{{ proxmox_ve__apt_repo_pve_no_subscription }}"
    state: present
    update_cache: yes

- name: Add enterprise repository
  ansible.builtin.apt_repository:
    repo: "{{ proxmox_ve__apt_repo_pve_enterprise }}"
    state: present
    update_cache: yes
  when:
    - proxmox_ve__enterprise

- name: Get list of installed packages
  ansible.builtin.package_facts:
    manager: apt

# Must install ifupdown2 before proxmox-ve otherwise network connection
# will be closed during upgrade
- name: Install ifupdown2
  ansible.builtin.apt:
    package: ifupdown2
    state: present
    update_cache: yes
  notify: Reboot Host
  when: 
    - "'proxmox-ve' not in ansible_facts.packages"
    - ansible_distribution_release == "bullseye"

- name: Install Proxmox VE software
  ansible.builtin.apt:
    package: proxmox-ve
    state: present
    update_cache: yes
  notify: Reboot Host
