---

- name: "Checking system OS"
  ansible.builtin.fail:
    msg: "This is not a Debian based distribution. Proxmox VE is not compatible"
  when: ansible_distribution != "Debian"

- name: "Preconfigure the Host"
  ansible.builtin.include_tasks: preconfig.yml

- name: "Install Proxmox VE packages"
  ansible.builtin.include_tasks: install-packages.yml

- name: "Configure network"
  ansible.builtin.include_tasks: config-network.yml
  tags: proxmox_ve__confnetwork

- name: "Reboot host"
  ansible.builtin.include_tasks: reboot-host.yml
  when: proxmox_ve__force_reboot

- name: "Configure Proxmox VE"
  ansible.builtin.include_tasks: config-pve.yml

- name: "Configure ISCSI storage"
  ansible.builtin.include_tasks: config-storage-iscsi.yml
  when: "proxmox_ve__storage_iscsi | length > 0"
  tags: proxmox_ve__confiscsi

- name: "Configure LVM storage"
  ansible.builtin.include_tasks: config-storage-lvm.yml
  when: "proxmox_ve__storage_lvm | length > 0"

- name: "Configure Supervision user"
  ansible.builtin.include_tasks: config-spv.yml
  when: proxmox_ve__spv_password is defined
