---

- name: "Checking system OS"
  fail:
    msg: "This is not a Debian based distribution. Proxmox VE is not compatible"
  when: ansible_distribution != "Debian"

- include: preconfig.yml

- include: install-packages.yml

- include: config-network.yml

- include: reboot-host.yml
  when: proxmox_ve__force_reboot

- include: config-storage-iscsi.yml
  when: "proxmox_ve__storage_iscsi | length > 0"

- include: config-storage-lvm.yml
  when: "proxmox_ve__storage_lvm | length > 0"

- include: config-spv.yml
  when: proxmox_ve__spv_password is defined
