---

- name: Setup /etc/hosts with node ip
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^[0-9\.]+[ \t]+(.*{{ ansible_hostname }}.*)'
    line: '{{ proxmox_ve__cluster_ip }} \1'
    backrefs: yes
    state: present
    backup: true

- name: Disable SMT
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*nosmt)\"[^\"]*)(\".*)'
    line: '\1 nosmt\2'
    backrefs: true
    state: present
    backup: true
  when: proxmox_ve__disable_smt
  notify:
    - Update-grub
    - Reboot Host
