---
# Automatic host reboot

- name: Force handlers to run now
  ansible.builtin.meta: flush_handlers

- name: "Wait host"
  ansible.builtin.wait_for_connection:
    delay: 60
    sleep: 5
    timeout: 1800

- name: "Regather facts"
  ansible.builtin.setup:
