---
# handlers file for proxmox_ve


- name: Update-grub
  ansible.builtin.command: update-grub
  register: grub_output
  changed_when: grub_output.rc != 0

- name: Reboot Host
  ansible.builtin.shell: sleep 2 && shutdown -r now "Ansible reboot"
  async: 1
  poll: 0
  ignore_errors: true
  when: proxmox_ve__force_reboot
  register: reboot_output
  changed_when: reboot_output.rc != 0

- name: Restart iscsid
  ansible.builtin.service:
    name: iscsid
    state: restarted

- name: Restart multipath
  ansible.builtin.service:
    name: multipath-tools
    state: restarted
